### ISSUE TITLE
stat = 'stdDev' with get_*()'s

### ISSUE THREAD

**Issue by joshualerickson** [joshualerickson/exploreRGEE#1]
Need to fix or somehow adapt 'stdDev' to be able to reduce multiple bands. Right now, it works if `param = 'NDVI'` one band only, if not then it won't reduce. I think this has to do with using `data$reduce(ee$Reducer$stdDev())` in data_stat().

**Comment by zackarno** [comment]
Howdy, 

I have been wrapping some commonly used `rgee/gee` sequences into functions and have been dumping them into  a custom package so that I and other colleagues can have them on-hand.   I've noticed the great work that you have done here and realized that there could be some overlap as I have started to write (and think about) some of the same functions you have already made. Instead of unnecessary replication in a separate package I would be happy to contribute if you are open to that.  

Anyways, I saw this issue and wondered either of the functions below might help solve your issue.


```{r}

reducer_fun<- function(reducer){switch(
    reducer,
    "mean" = ee$Reducer$mean(),
    "max" = ee$Reducer$mean(),
    "min" = ee$Reducer$min(),
    "median"= ee$Reducer$median(),
    "sum"= ee$Reducer$sum(),
    "sd" = ee$Reducer$stdDev(),
    NULL
  )
}
fun_sel <-  function(x){switch(x,

                               "mean" = function(x)x$reduce(ee$Reducer$mean()),
                               "max" = function(x)x$reduce(ee$Reducer$max()),
                               "min" = function(x)x$reduce(ee$Reducer$min()),
                               "median"= function(x)x$reduce(ee$Reducer$median()),
                               "sum"= function(x)x$reduce(ee$Reducer$stdDev()),
                               "sd" =  function(x)x$reduce(ee$Reducer$stdDev()),
                               NULL

)
}

```

**Comment by joshualerickson** [comment]
Hey @zackarno , thanks for reaching out! As you can see the package needs a facelift and more efficient code (I like the switch suggestion above 👍). I'm totally open to having you contribute (contributions/ideas)! We could do this a couple ways but I think creating a dev branch and then adding you as a contributor might be the easiest and best instead of PR's and such every time you have a idea or new dev, thoughts? There are a couple things I'd like to keep with the package and its dev but I'm open thoughts and suggestions;

* Stay up to date with rgee/rgeeExtra and relevant python extensions (eemont). (I'm slacking here....).
* Rethinking some arguments (meaning, use, etc) and functions.
* Maybe not be so tied into an API with get -> rr/band/viz and make more open to other functionality? 
* Finally, stay open to the community. 


Let me know what you think and I can get the pprocessstarted!  Have a good one. :)

**Comment by zackarno** [comment]
Hey, that sounds great. I'd be happy to contribute as suggested! write access on  a dev branch does seem like a good option. Perhaps I could work on this by updating the dev with small feature branches which I will try to continuously merge to the dev?  I am often creating functions to reduce code and simplify specific problems/concepts I encounter in my work. Therefore, please let me know if any of the ideas seem out of scope and I can keep them separated. All your bullet points sounds good btw!

**Comment by joshualerickson** [comment]
Alright @zackarno I added you to the repo as well as adding a dev branch. I'll work under `jle-workflow` branch and feel free to create a branch(s) to work with. We'll try to stay on point with dev and then when patches/features, etc I'll push to main. Sound good? Look forward to working with you and getting this package refined! I'll work on this issue above by adding the better code but I'm still not sure if `"sd" = ee$Reducer$stdDev()` will work for multiple bands 🤷‍♂️? If I remember right all the reducers work just fine for multiple bands except `sd`, which can only be used with a _selected_ band. Hopefully, that has changed or we can figure that out. Thanks again, have a good one!

**Comment by joshualerickson** [comment]
Sweet, ok this works! I added this `fun_sel()` to utils.R and runs smooth with the example data for all of the reducers.  👍
Also, I really like the `month_range=c(1,12),` argument instead of `c.low and c.high`; more explicit and easier to code! In addition, I think we could do that for masking but I wonder if we take masking out of the `get_*()` functions and create a function like below,

**Example**

```
forest_cover_loss <- get_any(huc, image_type = "Image",
                                              method = 'UMD/hansen/global_forest_change_2019_v1_7',
                                              param = 'lossyear')

mask_forest <- forest_cover_loss$image %>% mask(mask_range = c(0,14))

mask_forest %>% viz(band = 'lossyear', user_geom = huc)

```

I think I might do this, thoughts? Less clunky in the `get_*()`...
