### ISSUE TITLE
I want to add value to list to ee.Image.

### ISSUE THREAD

**Issue by eeedasc** [joshualerickson/exploreRGEE#19]
I want to add value to list to ee.Image.

MODDAY_ext_lst <- select(MODDAY_ext, LST_Day_1km)
print(MODDAY_ext_lst)
class(MODDAY_ext_lst)

Result:

> class(MODDAY_ext_lst)
[1] "data.frame"

> typeof(MODDAY_ext_lst)
[1] "list"

cal_value <- na_interpolation(MODDAY_ext_lst, option = "linear", maxgap = Inf)
class(cal_value)
typeof(cal_value)

Result:

> class(MODDAY_ext)
[1] "data.frame"

> typeof(MODDAY_ext)
[1] "list"

MODDAY_ext["LST_Day_1km"] <- cal_value["LST_Day_1km"]
print(MODDAY_ext)
class(MODDAY_ext)
typeof(MODDAY_ext)

Result:

> class(MODDAY_ext)
[1] "data.frame"

> typeof(MODDAY_ext)
[1] "list"

I want to add the created parameter(MODDAY_ext) to 'ee.Image' file. How can I do? Thank you.

**Comment by joshualerickson** [comment]
Hey thanks for reaching out. Before I can help would you mind providing a reproducible example (reprex)? This will help me help you. Right now I'm having a hard time seeing how this is a exploreRGEE issue? Thanks.
